-- Production rebuild for TAH APP / 5fedu after owner feedback.
-- Purpose: remove legacy text-id/HR-style tables and recreate the canonical int8 identity schema.
-- Required preflight before running on production: take a Supabase backup/export first.

begin;

drop table if exists public.vt_luong cascade;
drop table if exists public.vt_chuyen_xe_ct cascade;
drop table if exists public.vt_chuyen_xe cascade;
drop table if exists public.vt_dia_diem cascade;
drop table if exists public.vt_xe cascade;
drop table if exists public.vt_tai_xe cascade;
drop table if exists public.var_phan_quyen cascade;
drop table if exists public.var_nhan_vien cascade;
drop table if exists public.var_chuc_vu cascade;
drop table if exists public.var_phong_ban cascade;
drop table if exists public.var_cong_ty cascade;
drop table if exists public.phan_quyen cascade;
drop table if exists public.he_thong_nhan_vien cascade;
drop table if exists public.he_thong_chuc_vu cascade;
drop table if exists public.he_thong_phong_ban cascade;
drop table if exists public.he_thong_chi_nhanh cascade;

commit;
-- Initial canonical schema for TAH APP / 5fedu.
-- Rule nguá»“n: app table id = int8 identity, khÃ´ng uuid/text PK.

create or replace function public.set_tg_cap_nhat()
returns trigger
language plpgsql
as $$
begin
  new.tg_cap_nhat = now();
  return new;
end;
$$;

create table if not exists public.var_cong_ty (
  id int8 generated by default as identity primary key,
  ten_cong_ty text not null,
  logo text,
  dia_chi text,
  so_dien_thoai text,
  email text,
  trang_thai text not null default 'Äang hoáº¡t Ä‘á»™ng',
  tg_tao timestamptz not null default now(),
  tg_cap_nhat timestamptz not null default now()
);

create table if not exists public.var_phong_ban (
  id int8 generated by default as identity primary key,
  tt int4 not null default 0,
  ma_phong_ban text not null unique,
  ten_phong_ban text not null,
  mo_ta text,
  id_phong_ban_quan_ly int8 references public.var_phong_ban(id) on delete restrict,
  trang_thai text not null default 'Äang hoáº¡t Ä‘á»™ng',
  tg_tao timestamptz not null default now(),
  tg_cap_nhat timestamptz not null default now()
);

create table if not exists public.var_chuc_vu (
  id int8 generated by default as identity primary key,
  tt int4 not null default 0,
  ma_chuc_vu text not null unique,
  ten_chuc_vu text not null,
  mo_ta text,
  id_phong_ban int8 references public.var_phong_ban(id) on delete set null,
  cap_bac int2 not null default 4 check (cap_bac between 1 and 4),
  trang_thai text not null default 'Äang hoáº¡t Ä‘á»™ng',
  tg_tao timestamptz not null default now(),
  tg_cap_nhat timestamptz not null default now()
);

create table if not exists public.var_nhan_vien (
  id int8 generated by default as identity primary key,
  ho_va_ten text not null,
  avatar text,
  trang_thai text not null default 'Äang lÃ m viá»‡c',
  id_phong_ban int8 references public.var_phong_ban(id) on delete set null,
  id_chuc_vu int8 references public.var_chuc_vu(id) on delete set null,
  so_dien_thoai text,
  email text,
  ten_dang_nhap text unique,
  id_nguoi_tao int8 references public.var_nhan_vien(id) on delete set null,
  tg_tao timestamptz not null default now(),
  tg_cap_nhat timestamptz not null default now()
);

create table if not exists public.var_phan_quyen (
  id int8 generated by default as identity primary key,
  id_chuc_vu int8 not null references public.var_chuc_vu(id) on delete cascade,
  id_module text not null,
  quyen text not null check (quyen in ('xem', 'them', 'sua', 'xoa', 'quan_tri')),
  mo_ta text,
  tg_tao timestamptz not null default now(),
  tg_cap_nhat timestamptz not null default now(),
  unique (id_chuc_vu, id_module, quyen)
);

create table if not exists public.vt_tai_xe (
  id int8 generated by default as identity primary key,
  ho_ten text not null,
  trang_thai text not null default 'Äang hoáº¡t Ä‘á»™ng',
  id_nhan_vien int8 references public.var_nhan_vien(id) on delete set null,
  ghi_chu text,
  tg_tao timestamptz not null default now(),
  tg_cap_nhat timestamptz not null default now()
);

create table if not exists public.vt_xe (
  id int8 generated by default as identity primary key,
  hang text not null,
  model text not null,
  doi text,
  bien_so text not null unique,
  thong_tin_khac text,
  trang_thai text not null default 'Äang hoáº¡t Ä‘á»™ng',
  tg_tao timestamptz not null default now(),
  tg_cap_nhat timestamptz not null default now()
);

create table if not exists public.vt_dia_diem (
  id int8 generated by default as identity primary key,
  nhom text,
  ten text not null,
  mo_ta text,
  tien_luong numeric not null default 0,
  ghi_chu text,
  dinh_vi text,
  trang_thai text not null default 'Äang hoáº¡t Ä‘á»™ng',
  id_nguoi_tao int8 references public.var_nhan_vien(id) on delete set null,
  tg_tao timestamptz not null default now(),
  tg_cap_nhat timestamptz not null default now()
);

create table if not exists public.vt_chuyen_xe (
  id int8 generated by default as identity primary key,
  ngay date not null,
  id_tai_xe int8 not null references public.vt_tai_xe(id) on delete restrict,
  id_xe int8 references public.vt_xe(id) on delete set null,
  so_chuyen int4 not null default 0,
  tong_tien_luong numeric not null default 0,
  tong_phi numeric not null default 0,
  ghi_chu text,
  trang_thai text not null default 'Chưa duyệt',
  id_nguoi_tao int8 references public.var_nhan_vien(id) on delete set null,
  tg_tao timestamptz not null default now(),
  tg_cap_nhat timestamptz not null default now()
);

create table if not exists public.vt_chuyen_xe_ct (
  id int8 generated by default as identity primary key,
  id_chuyen_xe int8 not null references public.vt_chuyen_xe(id) on delete cascade,
  id_dia_diem int8 not null references public.vt_dia_diem(id) on delete restrict,
  tien_luong numeric not null default 0,
  chi_phi numeric not null default 80000,
  ghi_chu text,
  trang_thai text not null default 'ChÆ°a thá»±c hiá»‡n',
  phe_duyet text not null default 'ChÆ°a duyá»‡t',
  tg_tao timestamptz not null default now(),
  tg_cap_nhat timestamptz not null default now()
);

create table if not exists public.vt_luong (
  id int8 generated by default as identity primary key,
  nam int4 not null,
  thang int4 not null check (thang between 1 and 12),
  id_tai_xe int8 not null references public.vt_tai_xe(id) on delete restrict,
  tong_luong_chuyen numeric not null default 0,
  tong_chi_phi_chuyen numeric not null default 0,
  tong_chi_phi_khac numeric not null default 0,
  ghi_chu_chi_phi text,
  trang_thai text not null default 'ChÆ°a duyá»‡t',
  id_nguoi_tao int8 references public.var_nhan_vien(id) on delete set null,
  tg_tao timestamptz not null default now(),
  tg_cap_nhat timestamptz not null default now(),
  unique (nam, thang, id_tai_xe)
);

create index if not exists idx_var_phong_ban_parent on public.var_phong_ban(id_phong_ban_quan_ly);
create index if not exists idx_var_chuc_vu_phong_ban on public.var_chuc_vu(id_phong_ban);
create index if not exists idx_var_nhan_vien_phong_ban on public.var_nhan_vien(id_phong_ban);
create index if not exists idx_var_nhan_vien_chuc_vu on public.var_nhan_vien(id_chuc_vu);
create index if not exists idx_var_phan_quyen_chuc_vu on public.var_phan_quyen(id_chuc_vu);
create index if not exists idx_vt_chuyen_xe_ngay on public.vt_chuyen_xe(ngay);
create index if not exists idx_vt_chuyen_xe_id_tai_xe on public.vt_chuyen_xe(id_tai_xe);
create index if not exists idx_vt_chuyen_xe_ct_id_chuyen_xe on public.vt_chuyen_xe_ct(id_chuyen_xe);
create index if not exists idx_vt_luong_period on public.vt_luong(nam, thang);

do $$
declare
  t text;
begin
  foreach t in array array[
    'var_cong_ty',
    'var_phong_ban',
    'var_chuc_vu',
    'var_nhan_vien',
    'var_phan_quyen',
    'vt_tai_xe',
    'vt_xe',
    'vt_dia_diem',
    'vt_chuyen_xe',
    'vt_chuyen_xe_ct',
    'vt_luong'
  ]
  loop
    execute format('drop trigger if exists trg_%s_tg_cap_nhat on public.%I', t, t);
    execute format('create trigger trg_%s_tg_cap_nhat before update on public.%I for each row execute function public.set_tg_cap_nhat()', t, t);
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "%s authenticated all" on public.%I', t, t);
    execute format('create policy "%s authenticated all" on public.%I for all to authenticated using (true) with check (true)', t, t);
  end loop;
end $$;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on
  public.var_cong_ty,
  public.var_phong_ban,
  public.var_chuc_vu,
  public.var_nhan_vien,
  public.var_phan_quyen,
  public.vt_tai_xe,
  public.vt_xe,
  public.vt_dia_diem,
  public.vt_chuyen_xe,
  public.vt_chuyen_xe_ct,
  public.vt_luong
to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into public.var_cong_ty (id, ten_cong_ty, email, so_dien_thoai, trang_thai)
overriding system value
values (1, 'TAH APP', 'admin@gmail.com', '0900000000', 'Đang hoạt động')
on conflict (id) do update set
  ten_cong_ty = excluded.ten_cong_ty,
  email = excluded.email,
  so_dien_thoai = excluded.so_dien_thoai,
  trang_thai = excluded.trang_thai;

insert into public.var_phong_ban (id, tt, ma_phong_ban, ten_phong_ban, mo_ta, id_phong_ban_quan_ly, trang_thai)
overriding system value
values
  (1, 1, 'BGD', 'Ban giám đốc', 'Quản trị cấp cao', null, 'Đang hoạt động'),
  (2, 2, 'VT', 'Phòng Vận tải', 'Điều phối vận tải', null, 'Đang hoạt động'),
  (3, 3, 'HCNS', 'Phòng Hành chính Nhân sự', 'Nhân sự và hành chính', null, 'Đang hoạt động'),
  (4, 4, 'VT-DH', 'Nhóm Điều hành vận tải', 'Theo dõi chuyến xe', 2, 'Đang hoạt động')
on conflict (id) do update set
  tt = excluded.tt,
  ma_phong_ban = excluded.ma_phong_ban,
  ten_phong_ban = excluded.ten_phong_ban,
  mo_ta = excluded.mo_ta,
  id_phong_ban_quan_ly = excluded.id_phong_ban_quan_ly,
  trang_thai = excluded.trang_thai;

insert into public.var_chuc_vu (id, tt, ma_chuc_vu, ten_chuc_vu, cap_bac, id_phong_ban, mo_ta, trang_thai)
overriding system value
values
  (1, 1, 'ADMIN', 'Quản trị hệ thống', 1, 1, 'Toàn quyền ứng dụng', 'Đang hoạt động'),
  (2, 2, 'TP-VT', 'Trưởng phòng Vận tải', 2, 2, 'Quản lý vận tải', 'Đang hoạt động'),
  (3, 3, 'NV-VT', 'Nhân viên Vận tải', 4, 4, 'Nhập liệu vận tải', 'Đang hoạt động')
on conflict (id) do update set
  tt = excluded.tt,
  ma_chuc_vu = excluded.ma_chuc_vu,
  ten_chuc_vu = excluded.ten_chuc_vu,
  cap_bac = excluded.cap_bac,
  id_phong_ban = excluded.id_phong_ban,
  mo_ta = excluded.mo_ta,
  trang_thai = excluded.trang_thai;

insert into public.var_nhan_vien (id, ho_va_ten, avatar, trang_thai, id_phong_ban, id_chuc_vu, so_dien_thoai, email, ten_dang_nhap)
overriding system value
values
  (1, 'Admin', null, 'Đang làm việc', 1, 1, '0900000000', 'admin@gmail.com', 'admin'),
  (2, 'Nhân viên vận tải', null, 'Đang làm việc', 4, 3, '0900000001', 'vantai@gmail.com', 'vantai')
on conflict (id) do update set
  ho_va_ten = excluded.ho_va_ten,
  avatar = excluded.avatar,
  trang_thai = excluded.trang_thai,
  id_phong_ban = excluded.id_phong_ban,
  id_chuc_vu = excluded.id_chuc_vu,
  so_dien_thoai = excluded.so_dien_thoai,
  email = excluded.email,
  ten_dang_nhap = excluded.ten_dang_nhap;

insert into public.vt_tai_xe (id, ho_ten, trang_thai, id_nhan_vien, ghi_chu)
overriding system value
values
  (1, 'Xuyến', 'Đang hoạt động', 1, 'Tài xế chính từ dữ liệu sheet'),
  (2, 'Linh', 'Đang hoạt động', 2, 'Tài xế dự phòng')
on conflict (id) do update set
  ho_ten = excluded.ho_ten,
  trang_thai = excluded.trang_thai,
  id_nhan_vien = excluded.id_nhan_vien,
  ghi_chu = excluded.ghi_chu;

insert into public.vt_xe (id, hang, model, doi, bien_so, thong_tin_khac, trang_thai)
overriding system value
values
  (1, 'Hyundai', 'Porter', '2021', '51C-123.45', 'Xe vận tải chính', 'Đang hoạt động'),
  (2, 'Isuzu', 'QKR', '2020', '51D-678.90', 'Xe dự phòng', 'Đang hoạt động')
on conflict (id) do update set
  hang = excluded.hang,
  model = excluded.model,
  doi = excluded.doi,
  bien_so = excluded.bien_so,
  thong_tin_khac = excluded.thong_tin_khac,
  trang_thai = excluded.trang_thai;

insert into public.vt_dia_diem (id, nhom, ten, mo_ta, tien_luong, ghi_chu, dinh_vi, trang_thai, id_nguoi_tao)
overriding system value
values
  (1, 'Nội thành', 'Chợ Lớn', 'Điểm giao hàng trong dữ liệu sheet', 120000, '', 'Quận 5', 'Đang hoạt động', 1),
  (2, 'Ngoại thành', 'Phú Xuân', 'Tuyến phát sinh trong sheet', 180000, '', 'Nhà Bè', 'Đang hoạt động', 1),
  (3, 'Nội thành', 'PVĐồng', 'Điểm lặp lại theo dữ liệu sheet', 150000, '', 'Phạm Văn Đồng', 'Đang hoạt động', 1)
on conflict (id) do update set
  nhom = excluded.nhom,
  ten = excluded.ten,
  mo_ta = excluded.mo_ta,
  tien_luong = excluded.tien_luong,
  ghi_chu = excluded.ghi_chu,
  dinh_vi = excluded.dinh_vi,
  trang_thai = excluded.trang_thai,
  id_nguoi_tao = excluded.id_nguoi_tao;

insert into public.vt_chuyen_xe (id, ngay, id_tai_xe, id_xe, so_chuyen, tong_tien_luong, tong_phi, ghi_chu, trang_thai, id_nguoi_tao)
overriding system value
values
  (1, '2026-05-01', 1, 1, 3, 450000, 240000, 'Chợ Lớn, Phú Xuân, PVĐồng', 'Đã duyệt', 1),
  (2, '2026-05-02', 2, 2, 2, 300000, 160000, 'Dữ liệu mẫu từ sheet', 'Chưa duyệt', 1)
on conflict (id) do update set
  ngay = excluded.ngay,
  id_tai_xe = excluded.id_tai_xe,
  id_xe = excluded.id_xe,
  so_chuyen = excluded.so_chuyen,
  tong_tien_luong = excluded.tong_tien_luong,
  tong_phi = excluded.tong_phi,
  ghi_chu = excluded.ghi_chu,
  trang_thai = excluded.trang_thai,
  id_nguoi_tao = excluded.id_nguoi_tao;

insert into public.vt_chuyen_xe_ct (id, id_chuyen_xe, id_dia_diem, tien_luong, chi_phi, ghi_chu, trang_thai, phe_duyet)
overriding system value
values
  (1, 1, 1, 120000, 80000, '', 'Đã thực hiện', 'Đã duyệt'),
  (2, 1, 2, 180000, 80000, '', 'Đã thực hiện', 'Chưa duyệt'),
  (3, 1, 3, 150000, 80000, '', 'Đã thực hiện', 'Chưa duyệt')
on conflict (id) do update set
  id_chuyen_xe = excluded.id_chuyen_xe,
  id_dia_diem = excluded.id_dia_diem,
  tien_luong = excluded.tien_luong,
  chi_phi = excluded.chi_phi,
  ghi_chu = excluded.ghi_chu,
  trang_thai = excluded.trang_thai,
  phe_duyet = excluded.phe_duyet;

insert into public.vt_luong (id, nam, thang, id_tai_xe, tong_luong_chuyen, tong_chi_phi_chuyen, tong_chi_phi_khac, ghi_chu_chi_phi, trang_thai, id_nguoi_tao)
overriding system value
values
  (1, 2026, 5, 1, 450000, 240000, 0, '', 'Chưa duyệt', 1),
  (2, 2026, 5, 2, 300000, 160000, 50000, 'Phụ phí phát sinh', 'Chưa duyệt', 1)
on conflict (id) do update set
  nam = excluded.nam,
  thang = excluded.thang,
  id_tai_xe = excluded.id_tai_xe,
  tong_luong_chuyen = excluded.tong_luong_chuyen,
  tong_chi_phi_chuyen = excluded.tong_chi_phi_chuyen,
  tong_chi_phi_khac = excluded.tong_chi_phi_khac,
  ghi_chu_chi_phi = excluded.ghi_chu_chi_phi,
  trang_thai = excluded.trang_thai,
  id_nguoi_tao = excluded.id_nguoi_tao;

insert into public.var_phan_quyen (id_chuc_vu, id_module, quyen)
select 1, module_key, quyen
from (
  values
    ('phong-ban'), ('chuc-vu'), ('nhan-vien'), ('thong-tin-cong-ty'), ('phan-quyen'),
    ('chuyen-xe'), ('bang-luong'), ('thong-ke-chuyen-di'), ('thong-ke-luong'),
    ('tai-xe'), ('dia-diem'), ('danh-sach-xe')
) as modules(module_key)
cross join (
  values ('xem'), ('them'), ('sua'), ('xoa'), ('quan_tri')
) as permissions(quyen)
on conflict (id_chuc_vu, id_module, quyen) do nothing;

select setval(pg_get_serial_sequence('public.var_cong_ty', 'id'), coalesce((select max(id) from public.var_cong_ty), 1), true);
select setval(pg_get_serial_sequence('public.var_phong_ban', 'id'), coalesce((select max(id) from public.var_phong_ban), 1), true);
select setval(pg_get_serial_sequence('public.var_chuc_vu', 'id'), coalesce((select max(id) from public.var_chuc_vu), 1), true);
select setval(pg_get_serial_sequence('public.var_nhan_vien', 'id'), coalesce((select max(id) from public.var_nhan_vien), 1), true);
select setval(pg_get_serial_sequence('public.vt_tai_xe', 'id'), coalesce((select max(id) from public.vt_tai_xe), 1), true);
select setval(pg_get_serial_sequence('public.vt_xe', 'id'), coalesce((select max(id) from public.vt_xe), 1), true);
select setval(pg_get_serial_sequence('public.vt_dia_diem', 'id'), coalesce((select max(id) from public.vt_dia_diem), 1), true);
select setval(pg_get_serial_sequence('public.vt_chuyen_xe', 'id'), coalesce((select max(id) from public.vt_chuyen_xe), 1), true);
select setval(pg_get_serial_sequence('public.vt_chuyen_xe_ct', 'id'), coalesce((select max(id) from public.vt_chuyen_xe_ct), 1), true);
select setval(pg_get_serial_sequence('public.vt_luong', 'id'), coalesce((select max(id) from public.vt_luong), 1), true);
